name: CMake build and tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - synchronize
      - opened
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 1'  # Monday 20:00 UTC

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install extra dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y links python3-numpy-dev
    - name: Build
      run: |
        cmake .
        cmake --build . --parallel `nproc`
    - name: Test
      run: |
        ctest --parallel `nproc`
