name: make tests

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: create conda environments
      run: |
        conda create -y -n build -c conda-forge python=3.11 python-build
        conda create -y -n test -c conda-forge python=3.11 numpy matplotlib
    - name: install extra dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libjpeg-dev liblzma-dev
    - name: build
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate build
        make all
    - name: test
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate test
        make tests 2>&1 | tee test.out
    - name : check test output
      run: |
        ! grep ignored test.out
