name: Make build and tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - synchronize
      - opened
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 1'  # Monday 20:00 UTC

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install extra dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libjpeg-dev liblzma-dev links python3-build python3-dev python3-numpy-dev
    - name: Build
      run: |
        make all
    - name: Test
      run: |
        make tests 2>&1 | tee test.out
    - name : Check test output
      run: |
        ! grep -a ignored test.out
